// ─────────────────────────────────────────────────────────────────────────────
// ONE COMMAND, ARCHIVE → LIVE SITE.
//
//   npm run publish
//
// Re-reads the archive, rebuilds the site, commits whatever changed and pushes.
// GitHub Actions deploys from the push, so the site is live a minute or so
// later. Nothing here needs arguments; what to publish is whatever is in the
// archive.
//
//   npm run publish -- --dry     do everything except commit and push
//
// It stops rather than pushing when:
//   • the export fails
//   • nothing changed (no empty commits)
//   • the working tree has unrelated edits staged or unstaged — those are
//     someone's work in progress and must not be swept into an image commit
// ─────────────────────────────────────────────────────────────────────────────
import { execFileSync, spawnSync } from "node:child_process";

const DRY = process.argv.includes("--dry");

const git = (...args) => execFileSync("git", args, { encoding: "utf8" }).trim();

/**
 * Working-tree entries as [status, path]. Uses -z because a plain read has two
 * traps: paths with spaces get quoted, and trimming the output eats the leading
 * space of the first status code — which silently turned "package.json" into
 * "ackage.json" the first time this ran.
 */
const statusEntries = () =>
  execFileSync("git", ["status", "--porcelain", "-z"], { encoding: "utf8" })
    .split("\0")
    .filter(Boolean)
    .map((e) => [e.slice(0, 2), e.slice(3)]);
const run = (cmd, args) => {
  const r = spawnSync(cmd, args, { stdio: "inherit", shell: process.platform === "win32" });
  if (r.status !== 0) {
    console.error(`\n✗ ${cmd} ${args.join(" ")} failed — nothing was committed.`);
    process.exit(r.status ?? 1);
  }
};

// The pipeline only ever rewrites these. Anything else in the tree belongs to
// whoever was working before this ran.
const OWNED = [
  "public/images/",
  "src/content/image-manifest.json",
];

const dirty = statusEntries()
  .map(([, f]) => f)
  .filter((f) => !OWNED.some((o) => f.startsWith(o)));

if (dirty.length) {
  console.error("✗ the working tree has changes the image pipeline does not own:\n");
  for (const f of dirty) console.error("    " + f);
  console.error(
    "\n  Commit or stash them first. Publishing would otherwise fold someone's\n" +
      "  work-in-progress into a commit labelled as an image update.",
  );
  process.exit(1);
}

console.log("→ reading the archive\n");
run("npm", ["run", "images"]);

console.log("\n→ building the site\n");
run("npm", ["run", "build"]);

const files = statusEntries().map(([s, f]) => `${s} ${f}`);
if (!files.length) {
  console.log("\n✓ the archive matches what is already published — nothing to do.");
  process.exit(0);
}
console.log(`\n→ ${files.length} file${files.length > 1 ? "s" : ""} changed`);

if (DRY) {
  console.log("\n--dry: stopping before commit. Changed:\n" + files.map((f) => "  " + f).join("\n"));
  process.exit(0);
}

// Add only what the pipeline owns, by path — never `git add -A`.
run("git", ["add", "public/images", "src/content/image-manifest.json"]);

const staged = git("diff", "--cached", "--name-only").split("\n").filter(Boolean);
if (!staged.length) {
  console.log("\n✓ nothing staged — the change was outside the image pipeline.");
  process.exit(0);
}

const manifest = JSON.parse(
  execFileSync("node", ["-e", "process.stdout.write(require('fs').readFileSync('src/content/image-manifest.json','utf8'))"], {
    encoding: "utf8",
  }),
);
const slugs = manifest.order ?? Object.keys(manifest.collections);
const total = slugs.reduce((n, s) => n + manifest.collections[s].lookbook.length, 0);

const body =
  `Republish images from the archive\n\n` +
  `${slugs.length} collections, ${total} images.\n\n` +
  slugs.map((s) => `  ${s.padEnd(22)} ${String(manifest.collections[s].lookbook.length).padStart(3)}`).join("\n") +
  `\n\nGenerated by \`npm run publish\`.\n\n` +
  `Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>\n`;

run("git", ["commit", "-m", body]);
run("git", ["push", "origin", "HEAD"]);

console.log(
  "\n✓ pushed. GitHub Actions is building; the site updates in a minute or two.\n" +
    "  Check the served page, not the deploy status: a green run has shipped the\n" +
    "  previous commit before now.",
);
